### ISSUE TITLE
ckan does not start after upgrade from 2.6.2 to 2.6.6

### ISSUE THREAD

**Issue by taviroquai** [pduchesne/ckanext-geoview#12]
Hi all,

My ckan develop instance does not start after upgrading from 2.6.2 to 2.6.6

This is the error:
```bash
$ paster serve /etc/ckan/default/development.ini

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/serve.py", line 329, in loadapp
    **kw)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 45, in make_app
    load_environment(conf, app_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 97, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 139, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 153, in load
    service = _get_service(plugin)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 256, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: geojson_view

```

Any help is appreciated. Thanks!

**Comment by taviroquai** [comment]
@pduchesne Thanks for the hint but I'm not a pythonist and I have no idea of how ckan works so I'm just following the commands in the documentation.

I did installed the extension with:
```shell
$ . /usr/lib/ckan/default/bin/activate # Activate the virtual environment
$ cd /usr/lib/ckan/default/src/
$ git clone https://github.com/ckan/ckanext-geoview.git # download the extension
$ cd ckanext-geoview
$ python setup.py develop # install the extension
```

But still the error comes up... more help please!

**Comment by pduchesne** [comment]
There must be something wrong with your python env.

try `pip install -e .` instead of `python setup.py develop` .
It shouldn't make much of a difference, but it's worth a try.

I understand you're not familiar with python or ckan, but the procedure you describe is the developer installation, so it assumes some command of the python environment. You should stick to the regular install (using `pip install`) otherwise.

I'll close this, as it's not related to this extension per se. If it still doesn't work, try posting to ckan-users mailing list, this is where you would get support for this kind of problem.

**Comment by taviroquai** [comment]
Thanks @pduchesne 

Just for the record, I finally managed to run and I had to install more modules dependencies.
Now when I open the map preview for WMS/WFS, comes up a blank area and I see a 404 on the browser console for the file /css/bootstrap.min.css

Should I open a tiket here or in https://github.com/ckan/ckanext-geoview ?

Thanks

**Comment by pduchesne** [comment]
What viewer are you using ? Openlayers, leaflet ?

Please share your WMS url also.

**Comment by taviroquai** [comment]
Sorry the portal is not public yet.

I only have choice for OpenLayers, not for leaflet when creating a View.

I can see that the OL map is not initialized in the dom, although the ol lib and ol_preview.js are loaded by the browser.

There are no errors in the console.

I also tried with a static resource like KML but no map preview.
