### ISSUE TITLE
KeyError: 'ckanext'

### ISSUE THREAD

**Issue by jweyrich** [pduchesne/ckanext-geoview#5]
```
(default)[root@ckanhost1 default]# paster --plugin=ckanext-harvest harvester jobs
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib64/python2.7/site.py", line 890, in <module>
    main()
  File "/usr/lib/ckan/default/lib64/python2.7/site.py", line 848, in main
    virtualenv_search_paths(sys.prefix)
  File "/usr/lib/ckan/default/lib64/python2.7/site.py", line 638, in virtualenv_search_paths
    addsitedir(sitedir, known_paths)
  File "/usr/lib/ckan/default/lib64/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/ckan/default/lib64/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyError: 'ckanext'
```

Another user posted pretty much the same problem in a forked repo herehttps://github.com/ckan/ckanext-geoview/issues/39 - not sure which repository to post though. I am also not sure whether this is a problem related to `ckanext-geoview` or `ckan` itself.

**Could the problem be related to an update from ckanext-geoview-0.0.7 to ckanext-geoview-0.0.9?**

**Comment by jweyrich** [comment]
Alright, I did find out how to fix it. I deleted the package from the `sites-package` and manually installed version `0.0.7` from the `src/` directory as your README suggests. For some reason the problem caused the python interpreter to abort during startup as well - quite weird - so I went looking for it and found a relevant issue - http://bugs.python.org/issue10642.
